### ISSUE TITLE
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: Failed to fetch

### ISSUE THREAD

**Issue by ikexue** [bclswl0827/ChatGemini#17]
Frequent "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro: streamGenerateContent?alt=sse: Failed to fetch". streamGenerateContent?alt=sse: Failed to fetch", I don't know why?

**Comment by bclswl0827** [comment]
> Failed to fetch

It seems that you cannot connect to Google's API directly for various reasons.
If you're in China, please use some VPN/Proxy service to bypass the GFW and try again, or follow the README tutorial to set up a reverse proxy.

**Comment by ikexue** [comment]
thanks，my server is located in usa
