### ISSUE TITLE
给部署好的网站添加访问密钥

### ISSUE THREAD

**Issue by jxzzlfh** [bclswl0827/ChatGemini#2]
是不是再加个环境变量，可以给部署好的网站添加访问密钥，防止被人恶意滥用，被导致APIkey被封？

**Comment by bclswl0827** [comment]
后续更新会加上这一功能，用户可以自行选择是否公开站点

**Comment by jxzzlfh** [comment]
再加个，用户可以填入自己的API，来使用网站服务

**Comment by bclswl0827** [comment]
> 用户可以填入自己的APIkey，来使用网站服务

这个项目一开始就打算做成打开页面就能上手用的状态，所以也就不准备学 ChatGPTNextWeb 那样什么参数都能自定义，要不然光是配参数就太头疼了

**Comment by devyujie** [comment]
觉得目前这个优先级不高，反正 Gemini 是白嫖的，不想让别人用可以不公开网站。

**Comment by bclswl0827** [comment]
访问密钥功能已加上，请参考 README 中配置字段的部分
