### ISSUE TITLE
would you consider developing a separate chatgpt version or adding chatgpt support

### ISSUE THREAD

**Issue by ikexue** [bclswl0827/ChatGemini#21]
This is the best Gemini web app I've ever seen, It's amazing，would you consider developing a separate chatgpt version or adding interface support?

**Comment by bclswl0827** [comment]
Duplicate of https://github.com/bclswl0827/ChatGemini/issues/4
But leaving its interfaces is always a good design, I will try to improve it, so that you can fork and support other models by yourself with ease.

**Comment by ikexue** [comment]
Thanks
