### ISSUE TITLE
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: Load failed

### ISSUE THREAD

**Issue by siugix** [bclswl0827/ChatGemini#27]
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: Load failed

**Comment by siugix** [comment]
没用科学的时候出现这个错误

**Comment by bclswl0827** [comment]
https://github.com/bclswl0827/ChatGemini/issues/20#issuecomment-1940399412
