### ISSUE TITLE
我把端口改成80启动后进不去

### ISSUE THREAD

**Issue by do02fw** [bclswl0827/ChatGemini#29]
我的启动命令docker run -d \
    --name chatgemini \
    --restart always \
    --publish 80:80 \
    --env REACT_APP_GEMINI_API_KEY="xxx" \
    ghcr.io/bclswl0827/chatgemini
启动成功了，但是80进不去
![企业微信截图_20240311174425](https://github.com/bclswl0827/ChatGemini/assets/138294823/48da9240-ea6b-4114-a85f-7eaa512a9db2)
![企业微信截图_20240311174508](https://github.com/bclswl0827/ChatGemini/assets/138294823/dceb2a74-6671-4c94-a56d-a1a8b9fe2af1)

**Comment by do02fw** [comment]
我改成8080就可以访问

**Comment by bclswl0827** [comment]
请修改一下部署命令

> --publish 80:80

改为 

> `--publish 80:8080`

即可
