### ISSUE TITLE
期待增加 Vercel 部署方式

### ISSUE THREAD

**Issue by devyujie** [bclswl0827/ChatGemini#3]
期待增加 Vercel 部署方式，另外推荐一个[反代](https://github.com/antergone/palm-netlify-proxy)开源项目，作者可选择增加到 README 中以降低用户自部署门槛。

**Comment by devyujie** [comment]
使用方法就是，部署好之后，把这个网址拿来用就行了
![image](https://github.com/bclswl0827/ChatGemini/assets/48620527/f2550529-0119-4dde-9e01-f147e662dcaf)

**Comment by bclswl0827** [comment]
> 期待增加 Vercel 部署方式

Vercel 被墙了，感觉意义不太大，Netlify 倒是可以考虑

**Comment by chenweiask** [comment]
虽然Vercel被墙，但是可以通过绑定自己的域名来绕过。
有个GeminProChat的项目，就采取这样的方式。运行很稳定。
只是界面没有做成GPT这种对话模式，用起来不习惯。
同求Vercel～～～

**Comment by bclswl0827** [comment]
> 虽然Vercel被墙，但是可以通过绑定自己的域名来绕过。

已经新增 Vercel 部署方式，部署按钮和说明已经添加到 README

https://github.com/bclswl0827/ChatGemini#vercel-%E9%83%A8%E7%BD%B2

**Comment by chenweiask** [comment]
部署成功，谢谢大佬！！！
