### ISSUE TITLE
本地没有代理无法访问gemini

### ISSUE THREAD

**Issue by dengbojing** [bclswl0827/ChatGemini#6]
使用docker部署,部署服务端可以访问外网

如果本地没有代理, 浏览器无法访问gemini  

返回结果:
```
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: Failed to fetch
```

update: 
查看了一下请求, 直接页面发起谷歌请求, key直接在浏览器就能看到  
建议README写一下, 不要在公网部署

**Comment by bclswl0827** [comment]
> 使用docker部署,部署服务端可以访问外网
> 
> 如果本地没有代理, 浏览器无法访问gemini
> 
> 返回结果:
> 
> ```
> [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: Failed to fetch
> ```
> 
> update: 查看了一下请求, 直接页面发起谷歌请求, key直接在浏览器就能看到 建议README写一下, 不要在公网部署

Docker 版本没有内建反向代理，需要自己在配置指定，否则为直连

> 直接页面发起谷歌请求, key直接在浏览器就能看到

这是个纯前端项目，直连的话肯定避免不了的，如果介意的话，可以在前端这里的 API_KEY 随便填点字符串，在反向代理的位置修改请求头，替换成正确的 Key

**Comment by bclswl0827** [comment]
BTW, Google Gemini 的 API 随手就能免费申请，按常理来讲被盗用的几率很小

**Comment by dengbojing** [comment]
是的Gemini本身就是免费的, 只是习惯性觉得暴露api-key不太好, 我最后走的代理解决了
