### ISSUE TITLE
不会配置反向代理，，，

### ISSUE THREAD

**Issue by louis26wq** [bclswl0827/ChatGemini#7]
水平有限。
重装debian10后，按说明，手动部署，把项目配置在美国的vps上，必须开vpn才能和Gemini对话。
试了下  Nginx 反向代理 Gemini API  和  PHP 反向代理 Gemini API
不是报404 就是405 或者 500   ，都没成功，，，
不会配置，，，
能否给个更详细的？

**Comment by bclswl0827** [comment]
1. 每次修改 .env 后，需要重新 npm run build 构建前端
2. Nginx 最小配置可以参考项目根目录下 entrypoint.sh 第 12-28 行
3. 如果是 PHP 反向代理，PHP 需要支持 curl 且 Access Token 需要一致

如果还有问题，请把 API 返回的错误日志贴上来

**Comment by yrwy** [comment]
给个caddy的

> chat.hahahaha.com {
>         root * /home/ubuntu/ChatGemini/build
>         file_server
> 
> 	handle_path /api/* {
> 	reverse_proxy https://generativelanguage.googleapis.com {
>                 header_up Host {upstream_hostport}
>           }
> 	}
> }

api地址设置成 https://chat.hahahaha.com/api 即可

**Comment by louis26wq** [comment]
> 1. 每次修改 .env 后，需要重新 npm run build 构建前端
> 2. Nginx 最小配置可以参考项目根目录下 entrypoint.sh 第 12-28 行
> 3. 如果是 PHP 反向代理，PHP 需要支持 curl 且 Access Token 需要一致
> 
> 如果还有问题，请把 API 返回的错误日志贴上来


**### 感谢**，估计PHP反向代理用不了是因为没有配置 curl插件支持的原因。调整后现在正常了。。。
